name: MinecraftMinigames
main: io.github.brettcox.minecraftminigames.MinecraftMinigames
version: 1.00

commands:
   basic:
      description: This is a demo command.
      usage: /basic
      permission: 
      permission-message: You don't have <permission>
   basic2:
      description: This is another demo command.
      usage: /basic2
      permission:
      permission-message: You don't have <permission>